name: CI/CD Platform Pipeline

on:
  workflow_dispatch:
  push:
    branches: [trunk]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test workflow
        run: echo "Workflow is valid"
